all_urls = {
    'ADMIN_LOGIN_URL': 'XXX_ADMIN_LOGIN_URL_XXX',
    'USER_LOGIN_URL': 'XXX_USER_LOGIN_URL_XXX',
    'API_URL': 'XXX_API_URL_XXX',
    'ORCID_VALID_USERNAME' : 'XXX_ORCID_VALID_USERNAME_XXX',
    'ORCID_VALID_USERNAME_PASSWORD' : 'XXX_ORCID_VALID_USERNAME_PASSWORD_XXX',
    'ORCID_USER_EMAIL' : 'XXX_ORCID_USER_EMAIL_XXX'
}

